export const CHOOSE_ANSWER = 'CHOOSE_ANSWER';

export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';

export const NEXT_QUESTION = 'NEXT_QUESTION';

export const QUIT = 'QUIT';

export const FETCH_RESULTS_REQUEST = 'FETCH_RESULTS_REQUEST';

export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';

export const FETCH_RESULTS_FAILURE = 'FETCH_RESULTS_FAILURE';
